import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Autogenerated from the repository `/docs` tree (configured via docs.path).
 * Do not duplicate markdown here — the filesystem is the source of truth.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
